=== GerKowalski/mod-inventory-storage/ramls/instance.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "alternativeTitles": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    },
    "edition": {
      "type": "string"
    },
    "series": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    },
    "creators": {
      "type": "array",
      "minItems": 0,
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "creatorTypeId": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "creatorTypeId"
        ]
      }
    },
    "contributors": {
      "type": "array",
      "minItems": 0,
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "contributorTypeId": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "contributorTypeId"
        ]
      }
    },
    "publication": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "publisher": {
            "type": "string"
          },
          "place": {
            "type": "string"
          },
          "dateOfPublication": {
            "type": "string"
          }
        },
        "uniqueItems": true
      }
    },
    "date": {
      "type": "string",
      "format": "date-time"
    },
    "instanceTypeId": {
      "type": "string"
    },
    "instanceFormatId": {
      "type": "string"
    },
    "identifiers": {
      "type": "array",
      "minItems": 0,
      "items": {
        "type": "object",
        "properties": {
          "value": {
            "type": "string"
          },
          "typeId": {
            "type": "string"
          }
        },
        "additionalProperties": false,
        "required": [
          "value",
          "typeId"
        ]
      }
    },
    "subjects": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "source": {
      "type": "string"
    },
    "languageCodes": {
      "type": "array",
      "minItems": 0,
      "items": {
        "type": "string"
      }
    },
    "version" : {
      "type": "string"
    }
  },
  "additionalProperties": false,
  "required": [
    "title"
  ]
}

=== GerKowalski/mod-inventory-storage/sample-data/instances/bridgets-baby-instance.json
{
  "id": "7fbd5d84-62d1-44c6-9c45-6cb173998bbd",
  "title": "Bridget Jones's Baby",
  "alternativeTitles": ["First alternative title", 
                        "Second alternative title"],
  "identifiers": [
    { 
      "typeId": "7f907515-a1bf-4513-8a38-92e1a07c539d",
      "value": "B01LHE7MIU"
    }
  ],
  "creators": [
    {
      "creatorTypeId": "2e48e713-17f3-7c13-09f8-23845bb210aa",
      "name": "Creator A"
    },
    {
      "creatorTypeId": "e8b311a6-3b21-03f2-2269-dd9310cb2d0a",
      "name": "Creator B"
    }
  ],
  "contributors": [
    {
      "contributorTypeId": "2b94c631-fca9-a892-c730-03ee529ffe2b",
      "name": "Contributor 1"
    },
    {
      "contributorTypeId": "2e48e713-17f3-7c13-09f8-23845bb210ab",
      "name": "Contributor 2"
    }
  ],
  "publication": [
    {
      "publisher": "University of Oxford",
      "place": "UK",
      "dateOfPublication": "2017"
    },
    {
      "publisher": "Cambridge University Press",
      "place": "UK",
      "dateOfPublication": "2014"
    }
  ]
}
