=== GerKowalski/mod-inventory-storage/ramls/location.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "code": {
      "type": "string"
    },
    "isActive": {
      "type": "boolean"
    },
    "institutionId": {
      "type": "string",
      "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
    },
    "campusId": {
      "type": "string",
      "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
    },
    "libraryId": {
      "type": "string",
      "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
    },
    "details": {
      "type": "object"
    },
    "metadata": {
      "type": "object",
      "$ref": "raml-util/schemas/metadata.schema",
      "readonly": true
    }
  },
  "additionalProperties": false,
  "required": [
    "name",
    "code",
    "institutionId",
    "campusId",
    "libraryId"
  ]
}

=== GerKowalski/mod-inventory-storage/reference-data/locations/assorted.json
{
  "id": "53cf956f-c1df-410b-8bea-27f712cca7c0",
  "name": "Assorted Stacks",
  "code": "UU/OC/SL/A",
  "isActive": true,
  "institutionId": "6e068e4c-46e1-4cc5-8fcc-b9785dffb421",
  "campusId": "d9c58c68-da66-481d-9d90-78441970c8b6",
  "libraryId": "b77c9e17-65c6-41f7-9f42-e48e9b3b7783",
  "details": {
    "foo": "bar"
  }
}

=== GerKowalski/mod-inventory-storage/reference-data/locations/dusty.json
{
  "id": "fcd64ce1-6995-48f0-840e-89ffa2288371",
  "name": "Dusty Stacks",
  "code": "UU/OC/SL/D",
  "isActive": true,
  "institutionId": "6e068e4c-46e1-4cc5-8fcc-b9785dffb421",
  "campusId": "d9c58c68-da66-481d-9d90-78441970c8b6",
  "libraryId": "b77c9e17-65c6-41f7-9f42-e48e9b3b7783",
  "details": {
    "a": "b",
    "foo": "bar"
  }
}
